<%@ Page Title="Using the EntityDataSource" Language="C#" MasterPageFile="~/BasicTemplate.Master" AutoEventWireup="true" CodeBehind="EntityDataSource.aspx.cs" Inherits="BeginningASP.NET4._5.EntityFramework.EntityDataSource" %>

<asp:Content ID="Content2" ContentPlaceHolderID="header" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    
    <asp:EntityDataSource runat="server" ID="entityDataSource1" ConnectionString="name=NorthwindEntities1" EnableFlattening="false" DefaultContainerName="NorthwindEntities1" EntitySetName="Employees"  Select="it.[EmployeeID], it.[Title], it.[LastName], it.[FirstName], it.[City], it.[Country]">
    </asp:EntityDataSource>

    <asp:EntityDataSource runat="server" ID="entityDataSourceEmployeeDetails" ConnectionString="name=NorthwindEntities1" EnableFlattening="false" DefaultContainerName="NorthwindEntities1" EntitySetName="Employees" Where="" AutoGenerateWhereClause="true" EnableUpdate="true" EnableInsert="false">
        <WhereParameters>
            <asp:ControlParameter ControlID="gridViewEmployees" Name="EmployeeID" PropertyName="SelectedValue" />
        </WhereParameters>
    </asp:EntityDataSource>
    
    <asp:GridView runat="server" ID="gridViewEmployees" DataSourceID="entityDataSource1" AutoGenerateSelectButton="True" DataKeyNames="EmployeeID" CellPadding="4" ForeColor="#333333" GridLines="None">
        <AlternatingRowStyle BackColor="White" />
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        <SortedAscendingCellStyle BackColor="#FDF5AC" />
        <SortedAscendingHeaderStyle BackColor="#4D0000" />
        <SortedDescendingCellStyle BackColor="#FCF6C0" />
        <SortedDescendingHeaderStyle BackColor="#820000" />
    </asp:GridView>
    <br />
    <br />
    <asp:DetailsView runat="server" ID="detailsViewEmployee" DataSourceID="entityDataSourceEmployeeDetails" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="false" AutoGenerateEditButton="true" AutoGenerateInsertButton="false">
        <AlternatingRowStyle BackColor="White" />
        <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
        <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
    </asp:DetailsView>
</asp:Content>
